name: Terraform Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: <YOUR_AWS_REGION>
      AWS_ACCOUNT_ID: <YOUR_AWS_ACCOUNT_ID>
      AWS_ROLE_ARN: <YOUR_AWS_ROLE_ARN>
      AWS_ROLE_SESSION_NAME: GitHubActionsSession

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: aws configure set region ${AWS_REGION}

      - name: Assume AWS OIDC Role
        run: |
          aws sts assume-role-with-web-identity \
            --role-arn ${{ env.AWS_ROLE_ARN }} \
            --role-session-name ${{ env.AWS_ROLE_SESSION_NAME }} \
            --web-identity-token ${{ secrets.AWS_OIDC_TOKEN }} \
            --duration-seconds 900 # adjust the duration as per your requirement

      - name: Set AWS Credentials
        run: |
          export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Install Checkov
        run: pip install checkov

      - name: Checkov Scan
        run: checkov -d . --skip-check CKV_AWS_31,CKV_AWS_18_002

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Approval Step
        if: github.event_name == 'push'
        uses: unsplash/approvals-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
         
